### ISSUE TITLE
add openj9 to suite

### ISSUE THREAD

**Issue by adriaanm** [scala/compiler-benchmark#51]
The scala bugs should be ironed out in the latest builds, so that we can start running our benchmarks on J9. 

https://adoptopenjdk.net/releases.html?variant=openjdk8-openj9

**Comment by retronym** [comment]
I've installed the latest build of OpenJDK+J9 on the benchmark server and manually run a benchmark:

https://scala-ci.typesafe.com/view/scala-bench/job/compiler-benchmark/975/console

```
[info] Benchmark                                   (corpusVersion)  (extraArgs)  (resident)  (source)    Mode  Cnt     Score   Error  Units
[info] HotScalacBenchmark.compile                          a8c43dc                    false    scalap  sample   70  1543.744 ± 4.365  ms/op
```

That compares to a score of about 853ms for HotSpot.

To run alternative JDK-s regularly, we need to:

  - [ ] Change the result uploader to upload the JDK version as a tag, rather than a field.
  - [ ] Update the historical data to add this tag.
  - [ ] Update the Grafana views to include JDK version as a template filter field, with the right default
  - [ ] Schedule the alt-JDK runs (say, weekly)
  - [ ] Add a new view to Grafana to compare JDKs to encourage the vendors :)

**Comment by retronym** [comment]
Actually, we might be able to get rid of InfluxDB and migrate the data into Postgres, now that it is [supported by Grafana](http://docs.grafana.org/features/datasources/postgres/).

**Comment by retronym** [comment]
I recently implemented the multi-JDK change to support JDK 8/11/16 cross testing. OpenJ9 isn't a priority for us anymore so I'm not going to schedule the runs with that VM.
