### ISSUE TITLE
bigger codebase for benchmarks

### ISSUE THREAD

**Issue by adriaanm** [scala/compiler-benchmark#6]
(but, concern with jitter)

**Comment by lrytz** [comment]
- Include library / reflect / compiler
  - Since it's hard to keep a stable codebase for a very long time, we need a mechanism to get a source snapshot depending on the scala version being benchmarked
  - In the graphs, have a separate series for each version of a codebase
- Check the community build for other projects that could be built, e.g., parts of akka

**Comment by lrytz** [comment]
The core of this is done, corpus is versioned and library / reflect / compiler is in there. Still might need some refinements in the graph, this can come at its time.
